# Generated by Django 4.0.4 on 2022-05-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('email_Address', models.CharField(max_length=100)),
                ('Account_number', models.CharField(max_length=100, unique=True)),
                ('Transaction_ID', models.CharField(max_length=100, unique=True)),
                ('Deposited_Date', models.CharField(max_length=100)),
            ],
        ),
    ]
